/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasoRouteImport } from './routes/caso'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as SalonRouteImport } from './routes/salon'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasoRoute = CasoRouteImport.update({
  id: '/caso',
  path: '/caso',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonRoute = SalonRouteImport.update({
  id: '/salon',
  path: '/salon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caso': typeof CasoRoute
  '/menu': typeof MenuRoute
  '/reservar': typeof ReservarRoute
  '/salon': typeof SalonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caso': typeof CasoRoute
  '/menu': typeof MenuRoute
  '/reservar': typeof ReservarRoute
  '/salon': typeof SalonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caso': typeof CasoRoute
  '/menu': typeof MenuRoute
  '/reservar': typeof ReservarRoute
  '/salon': typeof SalonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/caso' | '/menu' | '/reservar' | '/salon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/caso' | '/menu' | '/reservar' | '/salon'
  id: '__root__' | '/' | '/caso' | '/menu' | '/reservar' | '/salon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasoRoute: typeof CasoRoute
  MenuRoute: typeof MenuRoute
  ReservarRoute: typeof ReservarRoute
  SalonRoute: typeof SalonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caso': {
      id: '/caso'
      path: '/caso'
      fullPath: '/caso'
      preLoaderRoute: typeof CasoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon': {
      id: '/salon'
      path: '/salon'
      fullPath: '/salon'
      preLoaderRoute: typeof SalonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasoRoute: CasoRoute,
  MenuRoute: MenuRoute,
  ReservarRoute: ReservarRoute,
  SalonRoute: SalonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
